apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mysite
        image: siddhudocker/mysite
        command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000


---

apiVersion: v1
kind: Service
metadata:
  name: mysite-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysite-service
                port:
                  number: 8000
